# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3408cce3e8908253c6fbbe5639beb30b1d9f2b18b38b0a6bd91e52af9dbc9d744c525a6f5766c029ce63120807188210de16b8fd197f39592e32e030493c620e

test:
  secret_key_base: ab3d45aceb64178d50894d2d42fac4b9ff503fa61dd7afd45f3e20d795f564aa3dccc320e59a7660abd9fc34b16da320e806462b1bfb540d3f52aa0146ea2d93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
